Add admin links to navbar
kir-dev/airsoft pull request #125
Opened 2021-08-15 19:57 UTC by poiuztrewq1

closes #71 
- Instead of a whole admin dashboard i created a drop-down menu for managing the website.
- Created a table for posts and events, because its easier to see through all of the entities this way, than in the landing page or calendar.
- Small typo fixes, and layout rearrangement in user list

2021-08-16 19:43 UTC, triszt4n requested changes
Loved it, some changes requested below

2021-08-16 19:43 UTC, triszt4n commented on app/views/events/list.html.erb
> +    <th>Jelntkezők</th>
Typo here

2021-08-16 19:43 UTC, triszt4n commented on app/views/layouts/_navbar.html.erb
> +        <% end %>
This could be moved down into the `navbar-nav me-right` list, so this button will be on the right (on the left it does not seem to be so important and admins might not find this button that easy)

2021-08-16 19:43 UTC, triszt4n commented on app/views/layouts/_navbar.html.erb
> +            <a class="nav-link dropdown-toggle text-muted" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
`text-muted` is not needed here (disables the hover effect). Pls add these html attibutes to this tag also: `title="Adminisztrátori opciók"` and `aria-label="Adminisztrátori opciók"`

2021-08-17 17:08 UTC, poiuztrewq1 commented
Rubocop doesn't like me. Its not a style issue, but somehow github actions suddenly can't run rubocop??? 
I will look into it, but if you approve i will force merge this, because local rubocop passes.

2021-08-17 17:29 UTC, triszt4n approved these changes
Forcepushes sometimes f*ck up all the workflows on GitHub so don't be bothered with that

2021-08-17 17:55 UTC, merged