Navigaton dropdown
kir-dev/airsoft pull request #41
Opened 2021-02-18 11:04 UTC by radikris

User page almost finished
Todo: link imagepopup.js to open image in modal

2021-02-20 09:31 UTC, SepsiLaszlo requested changes
Great work! 

I found some things that I do not fully understand.

Why do we need to create Scaffolds for Admins and Profiles? 
I think their functionality could easly fit into the UsersController.

Also the Rented Item is also weird because we already have Item + Rent models to model this.

2021-02-20 09:31 UTC, SepsiLaszlo commented on app/assets/stylesheets/profiles.scss
> +*{
These CSS rules (* and body) are applied on every page, which can be problematic. If we need them on all pages it should go to global.scss.

2021-02-20 09:31 UTC, SepsiLaszlo commented on app/assets/stylesheets/scaffolds.scss
> +body {
I think this auto generated file should be deleted, because it messes up the styling.

2021-02-20 09:31 UTC, SepsiLaszlo commented on app/controllers/rented_items_controller.rb
> +      params.fetch(:rented_item, {})
We shoul use the permit and require function for safe parameter mgmt.

2021-07-24 12:04 UTC, poiuztrewq1 commented
Closing this, because PR kind of got stuck and there are too much conflicting files.

2021-07-24 12:04 UTC, closed without merging