Add dynamic form creation for participations 2.0
kir-dev/airsoft pull request #46
Opened 2021-06-19 17:55 UTC by poiuztrewq1

Previous PR was good, but it can be better :point_right:
 - Added react_rails to render react components
 - With react components there is an intuitive GUI for building custom forms for admin users
 - There is a react component that renders the JSON schema to form
 
closes #16

2021-06-21 07:54 UTC, SepsiLaszlo requested changes
Nice work!
The  custom form building page is really awesome!
I found some minor things to improve.

2021-06-21 07:54 UTC, SepsiLaszlo commented on app/controllers/events_controller.rb
> +    @event_types = EventType.all.pluck(:name, :id)
In dynamically typed languages we expect variables to contain what their names suggests.
In this instance we expect an array of `EventType` records, but we get an array of arrays which contains only two values of the model.
Theory aside, if I understand correctly, this is line is only needed to event form. So we could move this logic to the form partial.
In most cases we try to resist putting logic into views but partials can be exceptions. Partials meant to be reusable so the logic need for them to work should be provided.
I made the suggestion in the corresponding file.
```suggestion
```

2021-06-21 07:54 UTC, SepsiLaszlo commented on app/controllers/events_controller.rb
> +    @event_types = EventType.all.pluck(:name, :id)
This also could be deleted.
```suggestion
```

2021-06-21 07:54 UTC, SepsiLaszlo commented on app/views/events/_form.html.erb
> +    <%= form.select :event_type_id, options_for_select(@event_types), include_blank: "Nincs jelentkezés" , class:"form-control" %>
This way the partial less context dependendent and more reusable.
```suggestion
    <%= form.select :event_type_id, options_for_select(EventType.all.pluck(:name, :id)), include_blank: "Nincs jelentkezés" , class:"form-control" %>
```
Maybe we could split this into multiple lines.

2021-06-21 07:54 UTC, SepsiLaszlo commented on app/controllers/participations_controller.rb
> +    elsif event.participations.exists?(:user => current_user)
I think it is better to stick to newer hash synstax insted of the hash rocket, if possible
```suggestion
    elsif event.participations.exists?(user: current_user)
```

2021-06-21 07:54 UTC, SepsiLaszlo commented on app/controllers/participations_controller.rb
> +      @participation = Participation.new(:event => event)
Here too:
```suggestion
      @participation = Participation.new(event: event)
```

2021-06-21 07:54 UTC, SepsiLaszlo commented on db/seeds.rb
> +Event.create(post: p2, event_type: et_short)
Please add the missing new line.

2021-06-23 13:41 UTC, triszt4n approved these changes

2021-06-23 16:24 UTC, SepsiLaszlo approved these changes

2021-06-23 16:30 UTC, merged